# Generated by Django 3.1.4 on 2021-01-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('registration_deadline', models.DateTimeField()),
                ('host_email', models.EmailField(max_length=254)),
                ('host_password', models.CharField(max_length=50)),
            ],
        ),
    ]
