# Generated by Django 3.1.4 on 2021-01-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_registration',
            old_name='event_name',
            new_name='eventName',
        ),
        migrations.RenameField(
            model_name='event_registration',
            old_name='from_date',
            new_name='fromDate',
        ),
        migrations.RenameField(
            model_name='event_registration',
            old_name='host_email',
            new_name='hostEmail',
        ),
        migrations.RenameField(
            model_name='event_registration',
            old_name='host_password',
            new_name='hostPassword',
        ),
        migrations.RenameField(
            model_name='event_registration',
            old_name='registration_deadline',
            new_name='registrationDeadline',
        ),
        migrations.RenameField(
            model_name='event_registration',
            old_name='to_date',
            new_name='toDate',
        ),
    ]
