# Generated by Django 3.1.4 on 2021-01-11 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0002_auto_20210112_0028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='event_registration',
            new_name='eventRegistration',
        ),
    ]
