# Generated by Django 3.1.4 on 2021-01-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0003_auto_20210112_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='participantRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participantName', models.CharField(max_length=50)),
                ('contactNumber', models.IntegerField()),
                ('participantEmail', models.EmailField(max_length=254)),
                ('eventName', models.CharField(max_length=50)),
                ('registrationType', models.CharField(max_length=50)),
                ('noOfPeople', models.IntegerField()),
            ],
        ),
    ]
