# Generated by Django 3.1.4 on 2021-01-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0005_auto_20210115_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantregistration',
            name='noOfPeople',
            field=models.PositiveIntegerField(),
        ),
    ]
