# Generated by Django 3.1.4 on 2021-01-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0006_auto_20210115_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='posterLink',
            field=models.URLField(default='NULL'),
        ),
    ]
