# Generated by Django 3.1.4 on 2021-01-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0007_eventregistration_posterlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantregistration',
            name='eventId',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
